language: go

go:
  - 1.15.2

script:
  - go build .
  - diff -u <(echo -n) <(gofmt -d ./)
  - go test github.com/maratona-run-time/Maratona-Runtime/verdict -v
  - go test github.com/maratona-run-time/Maratona-Runtime/compiler -v
  - go test github.com/maratona-run-time/Maratona-Runtime/tests -v