language: go

go:
  - 1.15.2

script:
  - go build .
  - diff -u <(echo -n) <(gofmt -d ./)
  - go test github.com/maratona-run-time/Maratona-Runtime/verdict/src -v
  - go test github.com/maratona-run-time/Maratona-Runtime/executor/src -v
  - go test github.com/maratona-run-time/Maratona-Runtime/compiler/src -v
  - go test github.com/maratona-run-time/Maratona-Runtime/executor/src -v
  - go test github.com/maratona-run-time/Maratona-Runtime/comparator/src -v
