apiVersion: v1
kind: Service
metadata:
  name: orchestrator
spec:
  selector:
    app: orchestrator
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: orm
spec:
  selector:
    app: orm
  ports:
  - port: 8084
    targetPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: postgress
spec:
  selector:
    app: postgress
  ports:
  - port: 5432
    targetPort: 5432
